import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  useAccountBalance,
  useAssetBalance,
  usePolkadotExtension,
  useSystemProperties,
  useApiProvider,
} from "@substra-hooks/core";
import { useEffect, useState } from "react";
import { xxhashAsHex } from "@polkadot/util-crypto";

const Home: NextPage = () => {
  const { accounts, w3enable, w3Enabled } = usePolkadotExtension();
  console.log("ACCOUNTS", accounts);

  const balancePayload = useAccountBalance(accounts?.[0]?.address || "");
  const assetPayload = useAssetBalance(
    accounts?.[0]?.address || "",
    8,
    "local"
  );
  useEffect(() => {
    if (!w3Enabled) {
      w3enable();
    }
  }, [w3enable, w3Enabled]);

  const [courses, setCourses] = useState<any[]>();
  const apiProvider = useApiProvider("local");
  useEffect(() => {
    async function init() {
      if (apiProvider) {
        const key = `0x${
          xxhashAsHex("Courses", 128).substr(2) +
          xxhashAsHex("Courses", 128).substr(2)
        }`;
        const keys = await apiProvider.rpc.state.getKeysPaged(key, 20);
        const courseIds: string[] = [];
        keys.forEach((item) => {
          const keyItem = item.toHuman()?.toString();
          const courseId = `0x${keyItem?.substring(keyItem.length - 64)}`;
          console.log("COURSE_ID", courseId);
          courseIds.push(courseId);
        });
        const courses: {
          id: string;
          name: string;
          owner: string;
        }[] = [];
        for (const courseId of courseIds) {
          const course: any = await apiProvider.query.courses.courses(courseId);
          courses.push({
            id: courseId,
            name: course.value.name.toHuman(),
            owner: course.value.owner.toHuman(),
          });
        }
        setCourses(courses);
      }
    }

    init();
  }, [apiProvider]);
  const systemProperties = useSystemProperties("local");
  console.log("systemProperties", systemProperties);

  console.log("accounts", accounts);

  console.log("balancePayload", accounts?.[5]?.address || "", balancePayload);
  console.log("assetPayload", assetPayload);
  return (
    <ul>
      {courses?.map((course) => (
        <li key={course.id}>
          {course.name} - Owner={course.owner}
        </li>
      ))}
    </ul>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/master/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  );
};

export default Home;
